server:
  port: 8761

spring:
  application:
    name: retail-bank-service-registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0

